language: ruby
before_script: rm -rf spec/fixtures/ephemeral_response/*
bundler_args: --without development
rvm:
  - 1.9.3
script: "bundle exec rake spec"
branches:
  only:
    - development
services:
  - mongodb
  - redis-server